language: node_js
node_js:
  - stable
script:
  - npm test
after_success:
- bash ./deploy.sh
env:
  secure: ZuY7ehXSlnqVjBICxEpwBvib+B0qt2CeEcjeS3YlKpxz8YiUQNb3+DF01fHX7mD4qrcs5LQL6+FoHrRdbmIVjmeRWwAnBlKa3a/UCs1BlIMt/2OaAlgA1tSoTuzbSmkkvRG42dmfm3709ov/Rg9juC5xm7dqBckk9MNY/ThiY8IaOYWBg0QjRb8gE2gDE6qZU93fDLe+k/hr4ajOy5jAW9jZ2hTmHxGvnCkyS5tYBI+CEFU2W1bWoiDrG60jcU2ZPFFa4czvgOglLbbviRVPMY7PzVbiZzIfJpZcAc6O4ogEdZ2o1XBgGcyEj7hgNiT+w3uCcwXfqFMm71ArzaZbqbQZCsllb2+5kgCO+o5jpECp7+ubhIzdX/86iV6yZ9nhmXHkLSWL8s1j+hd6IS5L5y2xdxL/Hs7q+jiEMV0ik64kvVKb9AhovV678f6ZOijqb8lJHI7JrBstUwOzGjR8XPzl8aQq7WpC84ndwC7dp06+DLWlQi2HAt7eJ2zAne/aBinlu/qlLafOIYA3ix5by7vYoYlXmXNYsNg5xU6Mpv+EfNpqUqlMbsN3pfaQnN3xUFxigjyzumcE0ssfipD1hiEy0uucOY90LmDE2Zpcs0v+PrfHJC3UaiAIZ+TsfY751by1A+6slgBhXr9J+7XT6Yx+swAKFcwDkK3UwF/R4AI=


